from __future__ import annotations

import itertools
import math
from dataclasses import dataclass
from statistics import NormalDist

import numpy as np
import pandas as pd
from pandas.api.types import is_bool_dtype, is_numeric_dtype

CSCV_BLOCK_COUNT = 16
_EULER_MASCHERONI = 0.5772156649015329


@dataclass(frozen=True)
class DeflatedSharpeResult:
    """Daily-scale Deflated Sharpe Ratio diagnostics.

    ``probability`` is the probabilistic Sharpe ratio against the expected
    maximum daily Sharpe generated by the disclosed trial universe. No annual
    scaling is applied anywhere in this result.
    """

    probability: float
    z_score: float
    observed_daily_sharpe: float
    expected_max_daily_sharpe: float
    trial_count: int
    trial_mean_daily_sharpe: float
    trial_std_daily_sharpe: float
    return_skewness: float
    return_kurtosis: float
    observations: int
    benchmark_source: str


@dataclass(frozen=True)
class PBOResult:
    """Result of a 16-block CSCV Probability of Backtest Overfitting test."""

    defined: bool
    pbo: float | None
    reason: str | None
    block_count: int
    block_sizes: tuple[int, ...]
    split_count: int
    logits: tuple[float, ...]
    oos_percentiles: tuple[float, ...]
    selection_counts: tuple[tuple[str, int], ...]


@dataclass(frozen=True)
class SPAInputs:
    """Validated losses ready for ``arch.bootstrap.SPA``.

    The optional ``arch`` package expects losses, where lower is better. The
    project stores daily net returns, so this adapter negates both benchmark
    and candidate returns without changing their common date index.
    """

    benchmark_losses: pd.Series
    candidate_losses: pd.DataFrame


def validate_daily_net_return_matrix(
    daily_net_returns: pd.DataFrame,
    *,
    minimum_rows: int = 2,
    minimum_candidates: int = 1,
) -> pd.DataFrame:
    """Validate and copy a common-date T-by-N daily net-return matrix.

    A DataFrame is required because a bare array cannot attest that every
    candidate was evaluated on exactly the same fixed date index. Missing and
    infinite values are rejected instead of being silently dropped or filled.
    """
    if not isinstance(daily_net_returns, pd.DataFrame):
        raise TypeError("daily_net_returns must be a pandas DataFrame")
    if isinstance(minimum_rows, bool) or not isinstance(minimum_rows, int):
        raise ValueError("minimum_rows must be an integer")
    if isinstance(minimum_candidates, bool) or not isinstance(
        minimum_candidates, int
    ):
        raise ValueError("minimum_candidates must be an integer")
    if minimum_rows < 1 or minimum_candidates < 1:
        raise ValueError("validation minimums must be positive")
    if len(daily_net_returns) < minimum_rows:
        raise ValueError(
            f"daily_net_returns must contain at least {minimum_rows} common dates"
        )
    if daily_net_returns.shape[1] < minimum_candidates:
        raise ValueError(
            "daily_net_returns must contain at least "
            f"{minimum_candidates} candidate columns"
        )
    if not isinstance(daily_net_returns.index, pd.DatetimeIndex):
        raise ValueError("daily_net_returns must use a common DatetimeIndex")
    if daily_net_returns.index.hasnans:
        raise ValueError("daily_net_returns date index cannot contain missing values")
    if not daily_net_returns.index.is_unique:
        raise ValueError("daily_net_returns date index must be unique")
    if not daily_net_returns.index.is_monotonic_increasing:
        raise ValueError("daily_net_returns date index must be sorted")
    if daily_net_returns.columns.has_duplicates:
        raise ValueError("candidate columns must be unique")
    if not all(
        isinstance(column, str) and column for column in daily_net_returns.columns
    ):
        raise ValueError("candidate columns must have non-empty string names")

    output = pd.DataFrame(index=daily_net_returns.index.copy())
    for column in daily_net_returns.columns:
        series = daily_net_returns[column]
        if is_bool_dtype(series.dtype) or not is_numeric_dtype(series.dtype):
            raise ValueError(f"candidate {column!r} must contain numeric returns")
        values = series.to_numpy(dtype=float, na_value=np.nan)
        if not np.isfinite(values).all():
            raise ValueError(
                f"candidate {column!r} contains a missing or infinite return"
            )
        output[column] = values
    output.index.name = daily_net_returns.index.name
    return output


def _daily_sharpe(values: np.ndarray, *, label: str) -> float:
    standard_deviation = float(np.std(values, ddof=1))
    if not math.isfinite(standard_deviation) or standard_deviation <= 0:
        raise ValueError(f"{label} has zero or invalid daily return volatility")
    sharpe = float(np.mean(values) / standard_deviation)
    if not math.isfinite(sharpe):
        raise ValueError(f"{label} has an invalid daily Sharpe ratio")
    return sharpe


def _expected_normal_maximum(mean: float, standard_deviation: float, trials: int) -> float:
    normal = NormalDist()
    first = normal.inv_cdf(1.0 - 1.0 / trials)
    second = normal.inv_cdf(1.0 - 1.0 / (trials * math.e))
    return mean + standard_deviation * (
        (1.0 - _EULER_MASCHERONI) * first + _EULER_MASCHERONI * second
    )


def deflated_sharpe_ratio(
    daily_net_returns: pd.DataFrame,
    *,
    selected_candidate: str,
    total_trials_evaluated: int | None = None,
    candidate_set_is_complete: bool = False,
) -> DeflatedSharpeResult:
    """Calculate a daily-scale Deflated Sharpe Ratio, failing closed on trials.

    There are exactly two accepted ways to disclose the search multiplicity:

    * set ``candidate_set_is_complete=True`` and supply the complete T-by-N
      candidate matrix; its daily Sharpe mean and dispersion parameterize the
      expected maximum; or
    * supply the complete ``total_trials_evaluated`` count. In this path the
      IID zero-Sharpe null standard error ``1 / sqrt(T - 1)`` is used, so a
      matrix containing only finalists cannot masquerade as the search space.

    ``total_trials_evaluated`` must count every candidate inspected, including
    discarded and invalidated research rounds. It must never be the number of
    post-selection survivors.
    """
    matrix = validate_daily_net_return_matrix(daily_net_returns)
    if not isinstance(selected_candidate, str) or not selected_candidate:
        raise ValueError("selected_candidate must be a non-empty string")
    if selected_candidate not in matrix.columns:
        raise ValueError("selected_candidate is not present in daily_net_returns")
    if not isinstance(candidate_set_is_complete, bool):
        raise ValueError("candidate_set_is_complete must be a boolean")

    observations = len(matrix)
    if total_trials_evaluated is None:
        if not candidate_set_is_complete:
            raise ValueError(
                "trial universe is undisclosed: provide total_trials_evaluated or "
                "explicitly attest candidate_set_is_complete=True"
            )
        trial_count = matrix.shape[1]
        if trial_count < 2:
            raise ValueError("a complete DSR candidate set must contain at least two trials")
        candidate_sharpes = np.array(
            [
                _daily_sharpe(matrix[column].to_numpy(), label=f"candidate {column!r}")
                for column in matrix.columns
            ]
        )
        trial_mean = float(np.mean(candidate_sharpes))
        trial_standard_deviation = float(np.std(candidate_sharpes, ddof=1))
        if trial_standard_deviation <= 0 or not math.isfinite(
            trial_standard_deviation
        ):
            raise ValueError("complete candidate daily Sharpes have zero dispersion")
        benchmark_source = "complete_candidate_matrix"
    else:
        if candidate_set_is_complete:
            raise ValueError(
                "choose one trial-universe source: a complete matrix or a total trial count"
            )
        if isinstance(total_trials_evaluated, bool) or not isinstance(
            total_trials_evaluated, (int, np.integer)
        ):
            raise ValueError("total_trials_evaluated must be an integer")
        trial_count = int(total_trials_evaluated)
        if trial_count < 2:
            raise ValueError("total_trials_evaluated must be at least two")
        if trial_count < matrix.shape[1]:
            raise ValueError(
                "total_trials_evaluated cannot be smaller than supplied candidates"
            )
        trial_mean = 0.0
        trial_standard_deviation = 1.0 / math.sqrt(observations - 1)
        benchmark_source = "complete_trial_count_iid_zero_sharpe_null"

    selected = matrix[selected_candidate].to_numpy()
    observed_sharpe = _daily_sharpe(
        selected, label=f"selected candidate {selected_candidate!r}"
    )
    centered = selected - float(np.mean(selected))
    second_moment = float(np.mean(centered**2))
    skewness = float(np.mean(centered**3) / second_moment**1.5)
    kurtosis = float(np.mean(centered**4) / second_moment**2)
    expected_maximum = _expected_normal_maximum(
        trial_mean, trial_standard_deviation, trial_count
    )
    variance_adjustment = (
        1.0
        - skewness * observed_sharpe
        + ((kurtosis - 1.0) / 4.0) * observed_sharpe**2
    )
    if variance_adjustment <= 0 or not math.isfinite(variance_adjustment):
        raise ValueError("selected return moments make the DSR variance invalid")
    z_score = (
        (observed_sharpe - expected_maximum)
        * math.sqrt(observations - 1)
        / math.sqrt(variance_adjustment)
    )
    probability = NormalDist().cdf(z_score)
    return DeflatedSharpeResult(
        probability=float(probability),
        z_score=float(z_score),
        observed_daily_sharpe=observed_sharpe,
        expected_max_daily_sharpe=float(expected_maximum),
        trial_count=trial_count,
        trial_mean_daily_sharpe=trial_mean,
        trial_std_daily_sharpe=trial_standard_deviation,
        return_skewness=skewness,
        return_kurtosis=kurtosis,
        observations=observations,
        benchmark_source=benchmark_source,
    )


def _undefined_pbo(reason: str, block_sizes: tuple[int, ...]) -> PBOResult:
    return PBOResult(
        defined=False,
        pbo=None,
        reason=reason,
        block_count=CSCV_BLOCK_COUNT,
        block_sizes=block_sizes,
        split_count=0,
        logits=(),
        oos_percentiles=(),
        selection_counts=(),
    )


def _sharpes_from_aggregates(
    sums: np.ndarray,
    sums_of_squares: np.ndarray,
    observations: int,
) -> np.ndarray | None:
    if observations < 2:
        return None
    variance_numerator = sums_of_squares - sums**2 / observations
    tolerance = np.finfo(float).eps * np.maximum(sums_of_squares, 1.0) * 32.0
    if np.any(variance_numerator <= tolerance):
        return None
    standard_deviations = np.sqrt(variance_numerator / (observations - 1))
    sharpes = (sums / observations) / standard_deviations
    return sharpes if np.isfinite(sharpes).all() else None


def _ascending_average_ranks(values: np.ndarray) -> np.ndarray:
    order = np.argsort(values, kind="stable")
    ranks = np.empty(len(values), dtype=float)
    start = 0
    while start < len(values):
        end = start + 1
        while end < len(values) and values[order[end]] == values[order[start]]:
            end += 1
        ranks[order[start:end]] = (start + 1 + end) / 2.0
        start = end
    return ranks


def cscv_probability_of_backtest_overfitting(
    daily_net_returns: pd.DataFrame,
) -> PBOResult:
    """Estimate PBO with combinatorially symmetric cross-validation.

    The fixed common-date panel is partitioned into 16 contiguous blocks. Each
    of the ``C(16, 8)`` train-block combinations selects the highest in-sample
    daily Sharpe, and the selected candidate is ranked on the complementary
    blocks. PBO is the share of OOS rank logits at or below zero.

    At least two observations per block and two candidates are required. A
    zero-volatility split or an in-sample winner tie makes the result explicitly
    undefined rather than allowing an arbitrary implementation choice to enter
    the estimate.
    """
    try:
        matrix = validate_daily_net_return_matrix(
            daily_net_returns,
            minimum_rows=CSCV_BLOCK_COUNT * 2,
            minimum_candidates=2,
        )
    except (TypeError, ValueError) as error:
        return _undefined_pbo(str(error), ())

    values = matrix.to_numpy()
    block_rows = np.array_split(np.arange(len(matrix)), CSCV_BLOCK_COUNT)
    block_sizes = tuple(len(rows) for rows in block_rows)
    if any(size < 2 for size in block_sizes):
        return _undefined_pbo(
            "CSCV requires at least two observations in each of 16 blocks",
            block_sizes,
        )

    block_sums = np.vstack([values[rows].sum(axis=0) for rows in block_rows])
    block_sums_of_squares = np.vstack(
        [(values[rows] ** 2).sum(axis=0) for rows in block_rows]
    )
    all_blocks = frozenset(range(CSCV_BLOCK_COUNT))
    logits: list[float] = []
    percentiles: list[float] = []
    selection_counts = np.zeros(matrix.shape[1], dtype=int)

    for train_tuple in itertools.combinations(
        range(CSCV_BLOCK_COUNT), CSCV_BLOCK_COUNT // 2
    ):
        train_blocks = np.fromiter(train_tuple, dtype=int)
        test_blocks = np.fromiter(all_blocks.difference(train_tuple), dtype=int)
        train_observations = int(sum(block_sizes[index] for index in train_tuple))
        test_observations = len(matrix) - train_observations
        train_sharpes = _sharpes_from_aggregates(
            block_sums[train_blocks].sum(axis=0),
            block_sums_of_squares[train_blocks].sum(axis=0),
            train_observations,
        )
        test_sharpes = _sharpes_from_aggregates(
            block_sums[test_blocks].sum(axis=0),
            block_sums_of_squares[test_blocks].sum(axis=0),
            test_observations,
        )
        if train_sharpes is None or test_sharpes is None:
            return _undefined_pbo(
                "a CSCV train/test split has zero or invalid candidate volatility",
                block_sizes,
            )
        winners = np.flatnonzero(train_sharpes == np.max(train_sharpes))
        if len(winners) != 1:
            return _undefined_pbo(
                "a CSCV in-sample split has a tied winner and no preregistered tie rule",
                block_sizes,
            )
        selected_index = int(winners[0])
        selection_counts[selected_index] += 1
        ranks = _ascending_average_ranks(test_sharpes)
        percentile = float(ranks[selected_index] / (matrix.shape[1] + 1.0))
        logit = math.log(percentile / (1.0 - percentile))
        percentiles.append(percentile)
        logits.append(logit)

    pbo = float(np.mean(np.asarray(logits) <= 0.0))
    counts = tuple(
        (column, int(selection_counts[index]))
        for index, column in enumerate(matrix.columns)
    )
    return PBOResult(
        defined=True,
        pbo=pbo,
        reason=None,
        block_count=CSCV_BLOCK_COUNT,
        block_sizes=block_sizes,
        split_count=len(logits),
        logits=tuple(logits),
        oos_percentiles=tuple(percentiles),
        selection_counts=counts,
    )


def prepare_spa_inputs(
    daily_net_returns: pd.DataFrame,
    *,
    benchmark_returns: pd.Series | None = None,
) -> SPAInputs:
    """Prepare validated common-date losses for an optional ``arch`` SPA run.

    This function intentionally performs no test and does not add ``arch`` as a
    hidden runtime dependency. A caller with the research extra installed can
    pass the returned objects to ``arch.bootstrap.SPA``.
    """
    matrix = validate_daily_net_return_matrix(daily_net_returns)
    if benchmark_returns is None:
        benchmark = pd.Series(0.0, index=matrix.index, name="benchmark_return")
    else:
        if not isinstance(benchmark_returns, pd.Series):
            raise TypeError("benchmark_returns must be a pandas Series")
        if not benchmark_returns.index.equals(matrix.index):
            raise ValueError(
                "benchmark_returns must have exactly the candidate matrix date index"
            )
        if is_bool_dtype(benchmark_returns.dtype) or not is_numeric_dtype(
            benchmark_returns.dtype
        ):
            raise ValueError("benchmark_returns must be numeric and non-boolean")
        values = benchmark_returns.to_numpy(dtype=float, na_value=np.nan)
        if not np.isfinite(values).all():
            raise ValueError("benchmark_returns cannot contain missing or infinite values")
        benchmark = pd.Series(values, index=matrix.index, name=benchmark_returns.name)

    benchmark_losses = (-benchmark).rename("benchmark_loss")
    candidate_losses = -matrix
    candidate_losses.index.name = matrix.index.name
    return SPAInputs(
        benchmark_losses=benchmark_losses,
        candidate_losses=candidate_losses,
    )
